### ISSUE TITLE
Integration of iD editor

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1358]
It shall be considered to integrate the iD editor into the Tasking Manager, this will support inexperienced mappers and improve mappers' workflows.

Related issue on the iD side: https://github.com/openstreetmap/iD/issues/5856

This can be explored to achieve possible features like:

* Shared actions in iD and TM (e.g. marking a task done from the editor)
* Simplify and target the editor for certain mapping purposes (e.g. by using [MapRules](https://github.com/radiant-maxar/maprules))
* Make external (meta) data available in iD

It is desired to use the upstream version in iD in the TM and contribute improvements to the main repository, and not maintaining a diverging fork on the TM's side.

**Comment by xamanu** [comment]
Talking with @quincylvania and @bhousel it was proposed to include this iD integration into the this year's [Google Summer of Code proposals from OSM](https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2019/Project_ideas#iD_Editor).

**Comment by bhousel** [comment]
I just added the Task Manager integration project to the [OpenStreetMap GSoC proposal page](https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2019/Project_ideas#iD_Editor)..

**Comment by thomas-hervey** [comment]
@xamanu I am going to apply for this year's GSoC and propose a project to work on this integration.

**Comment by xamanu** [comment]
The GSoC project has been finished and the created code is being reviewed by @quincylvania. We talked today and lined out the following steps forward:

* [ ] Review and merge GSoC code - https://github.com/openstreetmap/iD/issues/5856
* [ ] Main iD and self-hosted iD (containerized setup) - #1909 
* [ ] Add iD endpoints for interactions - TBD
* [ ] One Login through TM for self-hosted iD - #1910
* [ ] Sidebars in TM and direct interaction with iD - this issue here

**Comment by xamanu** [comment]
This has been implemented. Many thanks.
