### ISSUE TITLE
Improve campaigns

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1590]
Similarly as we are moving organizations from free tags to database objects (#1531) that can be referenced by project, that are grouped under one campaign. Campaigns should belong to none, one of several organizations and their admins will be able edit campaigns and add projects to them.

**Implementation steps:**

* [x] Implement database change for campaigns and changes to the Tasking Manager (filters for projects, etc.) #1606 
* [x] Add API views to associate and unassociate campaigns with users (in order to recommend projects based on their interest) #1607
* [x] Develop migration path for existing tags into campaigns. This fixes https://github.com/hotosm/tasking-manager/issues/943.
* [x] Allow editing of campaigns and associating it to organizations. If it is connected to an organization, admins of this organizations can edit, too.
* [x] Restrict the selection of campaigns to admins of associated organizations and campaigns without any affiliation to an organization.
* [x] Create campaign pages (https://github.com/hotosm/tasking-manager/issues/583)

**Comment by xamanu** [comment]
This will be targeted for the redesign with the new framework #1541.

**Comment by uwaiszaki** [comment]
@xamanu I have some doubts regarding the structure of campaigns part.
1) How projects and organisations should be connected to campaigns.
2) What should be the process to assign a campaign to a project? Whether it will be first assigned to the organization and then to the projects or should it be independently linked with the projects.

**Comment by uwaiszaki** [comment]
![gsocstructure1](https://user-images.githubusercontent.com/32809190/59446604-720b8a00-8e1f-11e9-862e-f932a2e84b21.png)
After discussion with @xamanu, we are going to use this structure for teams, organisations, and campaigns.
1) Structure for teams is based on the discussion in #1531.
2) user-interest-campaigns table will be used to show the recommended campaigns and projects to the users based on their previous searches. 
3) For many to many relations between campaigns and projects/organisations, campaign_projects and campaign_organisations will be used.
4) The process to assign a project to an organisation will be done by first assigning organisation to it and then assigning projects under that organisation.

**Comment by xamanu** [comment]
This is our proposal. @hotosm/tech and @zlavergne please let us know what you think. Thanks.

**Comment by verdy-p** [comment]
in your schema, "campaign_projects" references:
- (by foreign key organisation_id) "organisations".id, and
- (by foreign key project_id) and "projects".id
The projects table then references (by by foreign key organisation_id)
"organisations".id again

So it is not normalized, there's two possible organisations from the
same"campaign_project", unless you drop organisation_id from
"campaign_projects"... The foreign key constraints alone do not warranty
the organisations will be the same, unless you define a "role" for each
link (so a "campaign_project" can reference the organisation that created
it or decides, but then the organisation linked from the campaign_project
is the effective organizer/coordinator for that campaign project and but is
a delegate from the first one)... This is still not clear.


Le jeu. 13 juin 2019 à 17:54, uwais zaki <notifications@github.com> a
écrit :

**Comment by verdy-p** [comment]
[image: Annotation 2019-06-13 235430.png]
May be this image (created very rapidly in Ms Access) is clearer to
interpret your schema (all foreign key references are read from left to
right).

There's evidently something wrong (along the path marked in yellow). But
may be the "projects" table is superfluous and can be merged into
"campaign_projects" just above left (that will be renamed just "projects"),
so the "project_teams" will still reference this merged table. Also I see
no use of the "id" field in the projects table (it can be dropped in the
merged table)

So the new merged table "projects" will just have two foreign key fields:
campaign_id, and organisation_id (project_id is removed).

Also the name of the table "user_interest_campaigns" is overlong, should
should be "user_campaigns"... If you cant to mark a role for this relation
table, add a "role" field in it which can be set as an enum (e.g.:
participating, proposing, interested, refused to participate, banned) and
possibly a date to have an history.

You schema also makes clear that if a user joins a team which is freely
open, it will be part of an "organisation" which may be fictive and
assigned by default, but that fictive organisation may still have roles
assigned (this is what you call "organisation admins": that relation is the
best place to indicate an enumerated "role", for various kinds of
"adminship", e.g. coordinators, moderators, reviewers, educators,
promoters/advertizers...). Thanks your schema can be used because
"organisation admins is a relation table for many-to-many relations between
users and organisations.

**Comment by verdy-p** [comment]
Then here is how it looks after merging the two tables (I also added a
"name" field in the project table)
[image: Annotation 2019-06-14 001835.png]

**Comment by verdy-p** [comment]
Also I think you can merge the two similar relation tables for admins (of
an organization) and for team members (because they are also linked to a
unique organization); the admins are just a particular type of team, their
membership having some specific enumerated "function". As well the proposed
date field becomes two dates (min and max, for period of activities in that
function: if the max date is null, the role is still active, if the min
date is not set, it is just a project for a future position and the max
date is also normally null).
With that you can define various calendars/schedules for users in working
teams (including admins).
This time the schema becomes simpler:
[image: Annotation 2019-06-14 003219.png]

**Comment by uwaiszaki** [comment]
@verdy-p The image you are referencing is not visible. Can you please send it again? Thanks

**Comment by verdy-p** [comment]
I had attached three images (one per mail). May be your mail agent has
dropped the HTML part
They are now in attachment (their name indicates a timestamp, in the same
order as the 3 emails)

Le ven. 14 juin 2019 à 06:28, uwais zaki <notifications@github.com> a
écrit :

**Comment by xamanu** [comment]
Thanks @verdy-p for this input. Indeed it would be helpful to see the images you are referring to. Some of my first thoughts on the points you are raising:

> in your schema, "campaign_projects" references:
> - (by foreign key organisation_id) "organisations".id, and
> - (by foreign key project_id) and "projects".id
> The projects table then references (by by foreign key organisation_id) "organisations".id again
> 
> So it is not normalized, there's two possible organisations from the same"campaign_project", unless you drop organisation_id from "campaign_projects"... The foreign key constraints alone do not warranty the organisations will be the same, unless you define a "role" for each link (so a "campaign_project" can reference the organisation that created it or decides, but then the organisation linked from the campaign_project is the effective organizer/coordinator for that campaign project and but is a delegate from the first one)... This is still not clear.

I think we have to give a bit of input on this. Please also have a look on #1531 where we have defined the tables that are related to teams and organizations.

The basic idea behind the `Project.organisations_id`, is a required/obligatory connection to be understood as the "owner" of a project, mostly handled in #1531 and #1591.

Campaigns however are completely optional and they are meant to group projects under one communication umbrella. Secondly, they optionally will allow to assign organizations as “partners” (not “owner”)  to these grouped projects.

If we think about combining the `Project.organisation_id` and the table `project_campaigns` into one table `project_organisations` with an ENUM to select the main `owner` of a project and the ones that are `partner`. This would save us the `campaigns` table. But:
- We lose the gimme all projects assigned to one campaign.
- We store the same combination of organisations again and again for each project, where one reference to a campaign would be enough.
- it would make it hard to store information on campaigns (`name`, `logo`, `description`, maybe `url`).

> Also the name of the table "user_interest_campaigns" is overlong, should be "user_campaigns"...

Yes, I agree.

> If you cant to mark a role for this relation table, add a "role" field in it which can be set as an enum (e.g.: participating, proposing, interested, refused to participate, banned) and possibly a date to have a history.

For now it is not planned to have more than, "as a user I like this campaign". When we add more functionality we might want to extend this for roles and a date field. But for now a simple connection is probably enough.

> Also I think you can merge the two similar relation tables for admins (of an organization) and for team members (because they are also linked to a unique organization); the admins are just a particular type of team, their membership having some specific enumerated "function".

Team members are particularly not linked to a unique organization. They are completely free to be formed. Therefore they can not be merged with the purpose of managing the admins of an organization. Please have a look at the teams and organisations conversation (#1531) for more details on this relationship.

> As well the proposed date field becomes two dates (min and max, for period of activities in that function: if the max date is null, the role is still active, if the min date is not set, it is just a project for a future position and the max date is also normally null). With that you can define various calendars/schedules for users in working
teams (including admins).

Cool idea. But probably also something for the future, not on our table right now.

**Comment by verdy-p** [comment]
Le ven. 14 juin 2019 à 09:55, Felix D. <notifications@github.com> a écrit :

> Thanks @verdy-p <https://github.com/verdy-p> for this input. Indeed it
> would be helpful to see the images you are referring to. Some of my first
> thoughts on the points you are raising:
>
> in your schema, "campaign_projects" references:
>
>    - (by foreign key organisation_id) "organisations".id, and
>    - (by foreign key project_id) and "projects".id
>    The projects table then references (by by foreign key organisation_id)
>    "organisations".id again
>
> So it is not normalized, there's two possible organisations from the
> same"campaign_project", unless you drop organisation_id from
> "campaign_projects"... The foreign key constraints alone do not warranty
> the organisations will be the same, unless you define a "role" for each
> link (so a "campaign_project" can reference the organisation that created
> it or decides, but then the organisation linked from the campaign_project
> is the effective organizer/coordinator for that campaign project and but is
> a delegate from the first one)... This is still not clear.
>
> I think we have to give a bit of input on this. Please also have a look on
> #1531 <https://github.com/hotosm/tasking-manager/issues/1531> where we
> have defined the tables that are related to teams and organizations.
>
> The basic idea behind the Project.organisations_id, is a
> required/obligatory connection to be understood as the "owner" of a
> project, mostly handled in #1531
> <https://github.com/hotosm/tasking-manager/issues/1531> and #1591
> <https://github.com/hotosm/tasking-manager/issues/1591>.
>
> Campaigns however are completely optional and they are meant to group
> projects under one communication umbrella. Secondly, they optionally will
> allow to assign organizations as “partners” (not “owner”) to these grouped
> projects.
>
> If we think about combining the Project.organisation_id and the table
> project_campaigns into one table project_organisations with an ENUM to
> select the main owner of a project and the ones that are partner. This
> would save us the campaigns table. But:
>
>    - We lose the gimme all projects assigned to one campaign.
>    - We store the same combination of organisations again and again for
>    each project, where one reference to a campaign would be enough.
>    - it would make it hard to store information on campaigns (name, logo,
>    description, maybe url).
>
> Also the name of the table "user_interest_campaigns" is overlong, should
> be "user_campaigns"...
>
> Yes, I agree.
>
> If you cant to mark a role for this relation table, add a "role" field in
> it which can be set as an enum (e.g.: participating, proposing, interested,
> refused to participate, banned) and possibly a date to have a history.
>
> For now it is not planned to have more than, "as a user I like this
> campaign". When we add more functionality we might want to extend this for
> roles and a date field. But for now a simple connection is probably enough.
>
> Also I think you can merge the two similar relation tables for admins (of
> an organization) and for team members (because they are also linked to a
> unique organization); the admins are just a particular type of team, their
> membership having some specific enumerated "function".
>
> Team members are particularly not linked to a unique organization. They
> are completely free to be formed. Therefore they can not be merged with the
> purpose of managing the admins of an organization. Please have a look at
> the teams and organisations conversation (#1531
> <https://github.com/hotosm/tasking-manager/issues/1531>) for more details
> on this relationship.
>

That's not what your schema indicates: you defined foreign keys that makes
a reference from the team to an organization (may be that key may be null,
i.e. optional, but this does not change the model, and what I popose is
still compatible with that view). Here you're just speaking about the fact
that teams have their own primary key (id) and it contains a reference to
the organisation (by organisation_id) which may be null. Your "admins"
table just makes the organisation_id mandatory (not null), but beside that,
they are still a particular type of team (just distinguished by their
"function" field which can still give them different "administrative"
roles).

As well the proposed date field becomes two dates (min and max, for period
> of activities in that function: if the max date is null, the role is still
> active, if the min date is not set, it is just a project for a future
> position and the max date is also normally null). With that you can define
> various calendars/schedules for users in working
> teams (including admins).
>
> Cool idea. But probably also something for the future, not on our table
> right now.
>
That's just an extension with extra fields that can be used to filter the
memberships by date and create calendars/schedules/histories with simple
filters by query while keeping the requests simple for current active
member ships (where both dates will be not null and can be compared), you
can make your filters even simpler for the current use by adding a boolean
"inactive" field (null or false by default, true when
inactive/historic/future).

**Comment by verdy-p** [comment]
> Le ven. 14 juin 2019 à 06:28, uwais zaki <notifications@github.com> a
> écrit :
>
>> @verdy-p <https://github.com/verdy-p> The image you are referencing is
>> not visible. Can you please send it again? Thanks
>>
> For your info, this is posted now also on GitHub #1531
<https://github.com/hotosm/tasking-manager/issues/1531> because someone
else on this list refered to it.

**Comment by xamanu** [comment]
Backend and frontend are almost finished and are going to be part of TM4.
