### ISSUE TITLE
Improve Continuous Integration pipelines for robust testing and validation

### ISSUE THREAD

**Issue by eternaltyro** [hotosm/tasking-manager#5709]
This is an epic that tracks all updates and improvements to our CI processes.

## Test Objectives

1. Functional tests
2. Smoke tests
3. Integration tests

## DevOps Objectives

1. Build container images
2. Compliance checks over built container images
3. Better database backup in the CI pipeline

## Tasks involved

- [x] https://github.com/hotosm/tasking-manager/issues/3653
- [ ] https://github.com/hotosm/tasking-manager/issues/5677
- [x] https://github.com/hotosm/tasking-manager/issues/5669
- [x] https://github.com/hotosm/tasking-manager/issues/5539
- [x] https://github.com/hotosm/tasking-manager/issues/3653
- [x] https://github.com/hotosm/tasking-manager/issues/5691
- [x] https://github.com/hotosm/tasking-manager/issues/5688
- [x] https://github.com/hotosm/tasking-manager/issues/5659
- [x] https://github.com/hotosm/tasking-manager/issues/5498
- [ ] https://github.com/hotosm/tasking-manager/issues/5492
- [x] https://github.com/hotosm/tasking-manager/issues/5442
- [x] https://github.com/hotosm/tasking-manager/issues/4994
- [x] https://github.com/hotosm/tasking-manager/issues/3355
- [x] https://github.com/hotosm/tasking-manager/issues/5680
