### ISSUE TITLE
Improving network error handling

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5763]
**Is your feature request related to a problem? Please describe.**
Our app's current network error handling leaves much to be desired, often causing crashes or indefinite loading indicators.

_This is not an exhaustive list and includes nothing from the management sections. So feel free to add to this list if you encounter issues elsewhere. Or provide more details for each item._ 

### Landing Page

- [ ] The app displays hyphens for the stats numbers even after the endpoint API fails. Mentioned here https://github.com/hotosm/tasking-manager/pull/5749#pullrequestreview-1412981198

### Explore Projects Page
- [ ] The app crashes when the campaign, organization, location, or interests filters fail to fetch.

### My Contributions Page
- [ ] The header profile doesn't show any affiliated organizations if fetching organizations fail. ![teams](https://user-images.githubusercontent.com/51614993/236379659-a43457aa-6b57-41ef-9edd-0dd58e21b179.png)
- [ ] The teams will keep loading forever if fetching them fails.
![teams-contrib](https://user-images.githubusercontent.com/51614993/236379935-beae7687-e4e7-4c54-acbd-0b0b9d4c5c57.png)

### Project Detail Page
- [ ] Error handling for project detail loading only accounts for private project errors, and as a result, the fallback error handling displays "Project not found" when any other error occurs.
![project-not-found](https://user-images.githubusercontent.com/51614993/236380340-19bb5426-00aa-442d-9cb5-9113313fdbb8.png)
- [ ] The loading indicator for the contribution timeline section continues to show indefinitely, even after the API has failed.
![contrib-timeline-deet](https://user-images.githubusercontent.com/51614993/236380589-76166f0d-100e-43b0-878e-49fc6b76db67.png)
- [ ] The loading indicator for the contribution timeline section continues to show indefinitely, even after the API has failed.
![contributors-list](https://user-images.githubusercontent.com/51614993/236380663-37478230-3aa3-4e10-8996-8d2410cf0eec.png)
- [ ] The app crashes or becomes unresponsive when loading questions, comments, or navigating with pagination buttons.

### Project's Tasks Selection Page
- [ ] The app displays the "failed to fetch" text when it fails to retrieve the project's summary.
![tasks-list-page](https://user-images.githubusercontent.com/51614993/236380902-a66388a4-4175-4091-9459-f3e91aaa1c9f.png)
- [ ] The loading indicator for the contribution timeline section continues to show indefinitely, even after fetching activities for a project fails. 
![screencapture-127-0-0-1-3000-projects-1-tasks-2023-05-04-13_28_45](https://user-images.githubusercontent.com/51614993/236381060-5cf3595c-7fd6-4ff6-933d-1fb8fd5be45c.png)
- [ ] The app crashes when the user contributions endpoint fails.
- [ ] The app crashes when it fails to load the latest activities.

### Task Detail Modal
- [ ] The app does not display a loading indicator when loading comments or activities, and it shows an empty container instead of an error message when it fails to load.
![empty-activities](https://user-images.githubusercontent.com/51614993/236381345-c0e3d195-fb95-49d9-9052-70787fcdbd1a.png)
- [ ] When a comment POST fails, the app does not display any error message to inform the user.

### Task Action Page
- [ ] The app always navigates the user to the tasks page when failing to fetch information about the user's locked tasks, without handling the error. 
- [ ] The app experiences a forever loading issue on the task action page when failing to fetch the project summary.
![screencapture-127-0-0-1-3000-projects-1-map-2023-05-04-13_41_39](https://user-images.githubusercontent.com/51614993/236381518-eec39030-5efe-4dd8-bce6-1f2e9f9f00f2.png)
- [ ] When there is a failure to fetch project tasks, the app is currently crashing
- [ ] When the task history fails, the app provides no UI indication to inform the user of the failure. There is no loading indicator, and the app behaves the same as when there is no error
- [ ] When there is a failure to load priority areas, the app is not currently providing any response in the UI
- [ ] When submitting a task fails or when trying to select another task, the app is not currently providing any response in the UI
- [ ] The app always shows the same error message when attempting to split a task, regardless of the actual error.
![split task](https://user-images.githubusercontent.com/51614993/236381713-2aefa6bf-5355-4323-8d71-0689f6ad0dec.png)

### Project Stats Page
- [ ] When the app fails to load the project summary, the stats page becomes stuck in an indefinite loading state. 
![screencapture-127-0-0-1-3000-projects-2-2023-05-04-10_31_11](https://user-images.githubusercontent.com/51614993/236381892-a8b7c488-a901-4f04-821b-a1d708b1fba2.png)
- [ ] If loading project tasks fails, all stat numbers are shown as zero. 
![task-by-status-fails](https://user-images.githubusercontent.com/51614993/236381954-6d385d69-bc89-4dab-aa70-c6cd84bacf32.png)
- [ ] Loading the contributors' section leads to an indefinite loading state.
![contributors-forever](https://user-images.githubusercontent.com/51614993/236381999-ed9387f3-f587-4b5f-a637-30c9065f1bbc.png)
- [ ] Loading the project timeline leads to an indefinite loading state. 
![project-timeline](https://user-images.githubusercontent.com/51614993/236382030-d401e3ac-eabf-406f-b199-670b31cc986d.png)
- [ ] Loading the time statistics section leads to an indefinite loading state.
![timestatistics-forever](https://user-images.githubusercontent.com/51614993/236382074-5c6261f2-c72d-48ad-b70d-355bca399515.png)

**Comment by ramyaragupathy** [comment]
@Aadesh-Baral is tracking the backend work here -> https://github.com/hotosm/tasking-manager/issues/5197
